"""init schema

Revision ID: 05258d178128
Revises: 
Create Date: 2025-10-04 00:47:57.154835

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '05258d178128'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('books',
    sa.Column('serial_number', sa.String(length=6), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('author', sa.String(), nullable=False),
    sa.Column('is_borrowed', sa.Boolean(), nullable=False),
    sa.Column('borrowed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('borrowed_by', sa.String(length=6), nullable=True),
    sa.PrimaryKeyConstraint('serial_number')
    )
    op.create_index(op.f('ix_books_serial_number'), 'books', ['serial_number'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_books_serial_number'), table_name='books')
    op.drop_table('books')
    # ### end Alembic commands ###
